### ISSUE TITLE
Presto execution error

### ISSUE THREAD

**Issue by Remi42JP** [treasure-data/pytd#40]
Not sure if the error is due to PYTD or not, but connection using the PRESTO engine doesn't seem to work anymore (it was working just fine yesterday).

When running a simple code as below I get an "Internal Failure" error:
```
import pytd
td_client = pytd.Client(database='my_database', apikey='XXX', endpoint='https://api.treasuredata.com/', default_engine='presto')
td_client.query("select count(*) from mytable")
```

PrestoQueryError: PrestoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="Internal failure: [Ljava.lang.String;@51c95cf3 (of class [Ljava.lang.String;)", query_id=20190808_044649_00122_rpyj2)

If I switch the engine to "hive", the query execute just fine, but I have errors in other part of the code with another error "InternalError: job error: 535701608: error".

Any idea what could be the cause?

Thanks

**Comment by chezou** [comment]
@Remi42JP Thanks for letting us know. It was an issue of Treasure Data's server-side not client-side, and it has been resolved.

I'll close this issue, but if you have the same problem, could you please contact our support?
