### ISSUE TITLE
'pytd.Client' object has no attribute 'query_engine'

### ISSUE THREAD

**Issue by Antchouay12** [treasure-data/pytd#79]
Following code fails when replacing pandas_td by pytd.pandas_td:
```
#import pandas_td as td
import pytd.pandas_td as td
con = td.connect(apikey=td_api_key)
engine = con.query_engine(database='global', type='presto')
```

with error:
`AttributeError: 'Client' object has no attribute 'query_engine'`

**Comment by takuti** [comment]
@Antchouay12 Thank you for reporting the error. 

`Connection#query_engine` has already been [deprecated in pandas-td](https://github.com/treasure-data/pandas-td/blob/e8eff24fd4f42fe94cfc5d09d8539e295ce15ff7/pandas_td/td.py#L115-L120), and hence the function is not transferred to pytd. Would it be possible to update your code as follows?

Before:

```py 
engine = con.query_engine(database='global', type='presto')
```

After:

```py
engine = td.create_engine("presto:gloal", con=con)
```

See [`create_engine` API documentation](https://pytd-doc.readthedocs.io/en/latest/pandas_td.html#pytd.pandas_td.create_engine) for the detail.

**Comment by takuti** [comment]
As I commented above, we're not planning to enable the deprecated function. Closing the issue for now, but @Antchouay12 feel free to reopen if any.
