### ISSUE TITLE
Support Spark 3.0 via td-pyspark-ea

### ISSUE THREAD

**Issue by takuti** [treasure-data/pytd#92]
We have a separate package `td-pyspark-ea` for Spark 3.0:  https://treasure-data.github.io/td-spark/getting_started_py.html

**Comment by chezou** [comment]
Spark 3.0 has been released https://spark.apache.org/releases/spark-release-3-0-0.html

**Comment by takuti** [comment]
https://treasure-data.github.io/td-spark/release_notes.html

> Spark 2.4.x + Scala 2.11 support is deprecated as of December 2020. It is planned to migrate to Spark 3.x + Scala 2.12 for 2021.

It's time to follow the deprecation; we can simply use the latest version of `td-pyspark` instead of `td-pyspark-ea` for this purpose.
