### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by chezou** [treasure-data/pytd#98]
We have to wait pytd dependencies Python 3.9 support, especially for 
- PySpark
- td-spark
- pyarrow

As of Jan 12th 2021, the dependencies status are:
- td-spark [v20.10.0 supports Spark 3.0.1](https://treasure-data.github.io/td-spark/release_notes.html#v20-12-0)
- Spark 3.0.2 will support Python 3.9 https://issues.apache.org/jira/browse/SPARK-33371
- pyarrow 3.0.0, planned to be released this January, will support Python 3.9 https://issues.apache.org/jira/browse/ARROW-10905?src=confmacro

**Comment by chezou** [comment]
pyarrow 3.0.0 has been released https://pypi.org/project/pyarrow/3.0.0/

**Comment by chezou** [comment]
Note: we dropped Python 3.9 support as of 1.4.2.
We're planning to support 3.9 once td-spark and PySpark support 3.9 and Python packages are released on PyPI.

**Comment by robinbowes** [comment]
@chezou Do we have any plans to resume 3.9 (and 3.10?) support ?

**Comment by chezou** [comment]
@robinbowes I'm no longer with maintaining pytd anymore. It's up to @treasure-data/integrations team's decision now.

**Comment by robinbowes** [comment]
@chezou Thanks for confirmation.
